In [2]:
import numpy as np
def relu(x):
    return np.maximum(0, x)
def initialize_network():
    input_size = 5
    hidden_layer1_size = 3
    hidden_layer2_size = 2
    hidden_layer3_size = 3
    output_size = 1
    
    #Weights for each layer
    weights_layer1 = np.random.rand(input_size, hidden_layer1_size)
    weights_layer2 = np.random.rand(hidden_layer1_size, hidden_layer2_size)
    weights_layer3 = np.random.rand(hidden_layer2_size, hidden_layer3_size)
    weights_output = np.random.rand(hidden_layer3_size, output_size)
    
    #Biases for each layer
    biases_layer1 = np.random.rand(1,hidden_layer1_size)
    biases_layer2 = np.random.rand(1,hidden_layer2_size)
    biases_layer3 = np.random.rand(1,hidden_layer3_size)
    biases_output = np.random.rand(1,output_size)
    
    # Print the architecture
    print("Neural Network Architecture: ")
    print(f"Input Layer: {input_size} nodes")
    print(f"Hidden Layer 1: {hidden_layer1_size} nodes")
    print(f"Hidden Layer 2: {hidden_layer2_size} nodes")
    print(f"Hidden Layer 3: {hidden_layer3_size} nodes")
    print(f"Output Layer: {output_size} nodes")
    
    #Weights and biases Printing
    print("Weights and Biases:")
    print("Weights Layer 1:\n", weights_layer1)
    print("Biases Layer 1:\n", biases_layer1)
    print("Weights Layer 2:\n", weights_layer2)
    print("Biases Layer 2:\n", biases_layer2)
    print("Weights Layer 3:\n", weights_layer3)
    print("Biases Layer 3:\n", biases_layer3)
    print("Weights Output:\n", weights_output)
    print("Biases Output:\n", biases_output)
    
    #Compute activations for each node in the first hidden layer
    input_layer = np.random.rand(1, input_size)
    activations_hidden1 = relu(np.dot(input_layer, weights_layer1) + biases_layer1)
    
    #Compute activations for each node in the second hidden layer
    activations_hidden2 = relu(np.dot(activations_hidden1, weights_layer2) + biases_layer2)
    
    #Compute activations for each node in the third hidden layer
    activations_hidden3 = relu(np.dot(activations_hidden2, weights_layer3) + biases_layer3)
    
    print("Activations of Hidden Layer 1:\n", activations_hidden1)
    print("Activations of Hidden Layer 2:\n", activations_hidden2)
    print("Activations of Hidden Layer 3:\n", activations_hidden3)
    
initialize_network()

Neural Network Architecture: 
Input Layer: 5 nodes
Hidden Layer 1: 3 nodes
Hidden Layer 2: 2 nodes
Hidden Layer 3: 3 nodes
Output Layer: 1 nodes
Weights and Biases:
Weights Layer 1:
 [[0.52881892 0.9961255  0.28386563]
 [0.70918182 0.51603453 0.14448794]
 [0.84171182 0.63745681 0.99502407]
 [0.38574762 0.71998302 0.81307285]
 [0.39410965 0.77660126 0.26648687]]
Biases Layer 1:
 [[0.00196106 0.70562722 0.87634385]]
Weights Layer 2:
 [[0.80587053 0.35014331]
 [0.93048499 0.52443087]
 [0.1411273  0.76321161]]
Biases Layer 2:
 [[0.95442094 0.8122951 ]]
Weights Layer 3:
 [[0.81194604 0.54862079 0.79941932]
 [0.02560225 0.49739379 0.53588411]]
Biases Layer 3:
 [[0.02661529 0.0438789  0.95765961]]
Weights Output:
 [[0.02246094]
 [0.35948343]
 [0.10193963]]
Biases Output:
 [[0.86084602]]
Activations of Hidden Layer 1:
 [[1.01810344 2.33369517 1.87232103]]
Activations of Hidden Layer 2:
 [[4.21058443 3.82161614]]
Activations of Hidden Layer 3:
 [[3.54322462 4.25474121 6.37162552]]
